version: "3.2"
services:
  redis:
    image: redis
    hostname: redis
    ports:
     - "6379:6379"
    command: redis-server --requirepass '$REDIS_PASSWORD' --appendonly yes
    volumes:
     - ./redis-data:/data
    environment:
     - REDIS_PASSWORD